### ISSUE TITLE
Scanning Private Repos are failing

### ISSUE THREAD

**Issue by LukeHarrold** [anshumanbh/git-all-secrets#25]
After the newest update of my docker image, I am no longer able to use my ssh key to scan private repos. When I try, I am given the following stack trace during the cloning process:
```
exit status 128: Cloning into '/tmp/repos/org/[REDACTED]'...

fatal: cannot run ssh: No such file or directory
fatal: unable to fork

panic: exit status 128

goroutine 61 [running]:
main.gitclone(0xc420469950, 0x26, 0xc4200b3110, 0x22, 0xc42026b280)
	/go/src/github.com/anshumanbh/git-all-secrets/main.go:97 +0x3bf
main.executeclone.func1.1()
	/go/src/github.com/anshumanbh/git-all-secrets/main.go:137 +0x4e
main.enqueueJob.func1(0xc420553c80)
	/go/src/github.com/anshumanbh/git-all-secrets/main.go:67 +0x27
created by main.enqueueJob
	/go/src/github.com/anshumanbh/git-all-secrets/main.go:66 +0x5b
```
I imaged my machine before I pulled the latest image, and the same command runs fine. For context, here is the command I am trying:
`docker run -it -v ~/.ssh/[REDACTED]:/root/.ssh/id_rsa abhartiya/tools_gitallsecrets -token=[REDACTED] -org=[REDACTED] -scanPrivateReposOnly -orgOnly`

**Comment by anshumanbh** [comment]
`fatal: cannot run ssh: No such file or directory` - This message tells me something is wrong with the way the repo is trying to be cloned. 

I don't have access to any private repos within an org. I can't really test this to see what's going on. If you have an org and some private repos in that org, do you mind adding me to that so that I can see whats going on here? Please re-open this ticket again if you can do that otherwise I am left with nothing to debug this.
