### ISSUE TITLE
index-pack-failed

### ISSUE THREAD

**Issue by jaikishantulswani** [anshumanbh/git-all-secrets#27]
Hello @anshumanbh ,
I am still getting the issue after cloning half of the repo from any org.
`exit status 128: Cloning into '/tmp/repos/org/xxx/est4js'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
`

**Comment by anshumanbh** [comment]
@jaikishantulswani I've seen this every now and then. I think this happens mostly when some repos/gists are badly configured/have been through multiple state changes and the code right now doesn't handle it very well. I thought I fixed it here - https://github.com/anshumanbh/git-all-secrets/commit/a78e6f22a088d2fdc4c4a4f2e460b10ee84d48a3 so that it continues to move on and not panic at such situations. Are you sure you are using the latest docker image/code? Please reopen this once you;ve ensured its the latest code
