### ISSUE TITLE
"results.txt" has shell color characters in it

### ISSUE THREAD

**Issue by breeze7086** [anshumanbh/git-all-secrets#28]
Example:

Tool: truffleHog
OrgorUser: terraform RepoName: fluentd-sumologic
~~~~~~~~~~~~~~~~~~~~~
^[[92mReason: Generic Password^[[0m
^[[92mDate: 2018-03-28 21:58:30^[[0m
^[[92mHash: e05234bc366d0ab0f5174f1085d84c032dd8b8a6^[[0m
^[[92mFilepath: aaa/bbb.txt^[[0m
^[[92mBranch: origin/master^[[0m
^[[92mCommit: Updated s3 key for remote state
^[[0m
^[[93m+  password = "admin"^[[0m
~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~

**Comment by anshumanbh** [comment]
This is because of trufflehogs output. That contains these characters and I am simply taking the output and lumping them together in this wrapper. Id recommend opening the results file in a shell to see the colored output. I dont think I can provide any support wrt the trufflehogs output itself unfortunately.
