### ISSUE TITLE
No Result

### ISSUE THREAD

**Issue by jaikishantulswani** [anshumanbh/git-all-secrets#33]
Hello @anshumanbh ,

I run git-all-secrets on some repo which already having some sensitive info but generated the results file is showing blank..no result.

I ran ./git-all-secrets -token=xxxmytokenxxxx -repoURL=https://github.com/some/info -toolName=thog -thogEntropy

Cloning of: https://github.com/some/info finished

Starting to scan: https://github.com/some/info

Finished truffleHog Scanning for: some_info
Scanning of: https://github.com/some/info finished

Combining the output into one file

Can you please help me out on this issue.

**Comment by anshumanbh** [comment]
@jaikishantulswani I'd need the repo URL you are trying to scan and the secret you're trying to find to troubleshoot exactly why its not finding it. Couple of things that come to my mind are - are you sure the secret can be found by the trufflehog regular expression file that you are providing? Please reopen this issue with more info because I can't really help you with the info you've provided me right now.
