### ISSUE TITLE
After cloning I get error

### ISSUE THREAD

**Issue by justpentest** [anshumanbh/git-all-secrets#4]
panic: exit status 128
goroutine 110 [running]:
main.check(0x7c8460, 0xc4201922c0)
        /data/main.go:40 +0x174
main.gitclone(0xc42024d3e0, 0x24, 0xc42016f4c0, 0x15, 0xc42022ffe0)
        /data/main.go:53 +0x108
created by main.cloneorgrepos
        /data/main.go:92 +0x429

Windows 10  git-all-secrets docker is being used.

**Comment by anshumanbh** [comment]
@justpentest Are you trying to run this on an org that has a lot of repositories and also a lot of users who in turn have a lot of repositories too? I'd recommend to start small and scan per user and see if this error still persists. I am aware of this goroutine error and I believe this is because the machine you are running this tool on, likely does not have the memory to handle so many goroutines that are spawned.
