### ISSUE TITLE
No output generated

### ISSUE THREAD

**Issue by Pitenager** [anshumanbh/git-all-secrets#50]
Hi dude, 

First of all, thank you for your tool, it seems to be very useful for the use-case that I'm currently covering.
However, I'm having a trouble and  I can't find what am I missing.
I'm running the tool in the following way:
```
docker run --rm -it abhartiya/tools_gitallsecrets -repoURL https://github.com/XXXX/XXXX -token XXXXXXX -output test.txt
```
And, after finish the scan, no matter what repo, org or user is scanning, it never drops any output.
I attach a pic to show you the case.
![imagen](https://user-images.githubusercontent.com/32803812/80205535-0f803e80-862b-11ea-8c25-b25d1c3e9de2.png)

I'm using the latest image and running on Ubuntu 18.04.

Any idea ?

Thank you !

**Comment by anshumanbh** [comment]
Hi @Pitenager what you are running is essentially a docker container. The output gets saved inside the container, not on your host. So, in order to get to the results, you'd have to copy the results from inside the container to your host. Take a look at this - https://www.shellhacks.com/docker-cp-command-copy-file-to-from-container/ to understand how you can do this. I hope this is helpful!
